# Generated by Django 3.2.9 on 2021-12-02 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject3', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stats',
            old_name='title',
            new_name='RunningBack',
        ),
    ]
