# Generated by Django 3.2.9 on 2021-12-02 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject3', '0002_rename_title_stats_runningback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver', models.CharField(max_length=255)),
            ],
        ),
    ]
