# Generated by Django 3.2.9 on 2021-12-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoProject3', '0004_auto_20211202_0704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Yard',
        ),
    ]
